#!/bin/bash
apt-get update -y; apt-get upgrade -y; apt-get dist-upgrade -y; apt-get autoremove -y
apt-get install build-essential libssl-dev curl nano wget zip unzip git lsof iftop htop vim -y
apt-get install ca-certificates apt-transport-https -y
wget -q https://packages.sury.org/php/apt.gpg -O- | sudo apt-key add -
echo "deb https://packages.sury.org/php/ stretch main" | sudo tee /etc/apt/sources.list.d/php.list
apt-get update -y; apt-get upgrade -y;
apt install -y php7.3 php7.3-cgi php7.3-bcmath php7.3-bz2 php7.3-cli php7.3-common php7.3-curl php7.3-dba php7.3-dev php7.3-enchant php7.3-fpm php7.3-gd php7.3-gmp php7.3-imap php7.3-interbase php7.3-intl php7.3-json php7.3-ldap php7.3-mbstring php7.3-mysql php7.3-odbc php7.3-opcache php7.3-pgsql php7.3-phpdbg php7.3-pspell php7.3-readline php7.3-recode php7.3-snmp php7.3-soap php7.3-sqlite3 php7.3-sybase php7.3-tidy php7.3-xml php7.3-xmlrpc php7.3-xsl php7.3-zip
curl -s https://raw.githubusercontent.com/theraw/web-pro/master/plus/php/7.3/fpm/www.conf > /etc/php/7.3/fpm/pool.d/www.conf
ex -sc '%s/;cgi.fix_pathinfo=1/cgi.fix_pathinfo=0/g|x' /etc/php/7.3/fpm/php.ini
ex -sc '%s/output_buffering = 4096/output_buffering = Off/g|x' /etc/php/7.3/fpm/php.ini
perl -pi -e 's/error_reporting = E_ALL & ~E_DEPRECATED & ~E_STRICT/error_reporting = E_ALL/g' /etc/php/7.3/fpm/php.ini
perl -pi -e 's/;error_log = syslog/error_log = php_error.log/g' /etc/php/7.3/fpm/php.ini
perl -pi -e 's/;date.timezone =/date.timezone = UTC/g' /etc/php/7.3/fpm/php.ini
useradd nginx
service php7.3-fpm restart
apt-get install -y libxml2-dev libbz2-dev libcurl4-openssl-dev libmcrypt-dev libmhash2 libmhash-dev libpcre3 libpcre3-dev
apt-get install -y libxslt1-dev libpopt0 libpq-dev libpq5 libpspell-dev libpthread-stubs0-dev libpython-stdlib libqdbm-dev libqdbm14
apt-get install -y libquadmath0 librecode-dev librecode0 librtmp-dev libsasl2-dev libsasl2-modules libsctp-dev libsctp1 libsensors4
apt-get install -y libsensors4-dev libsm-dev libsm6 libsnmp-base libsnmp-dev libsnmp-perl libsnmp30 libsqlite3-dev libssh2-1 libssh2-1-dev
apt-get install -y libsybdb5 libtasn1-6-dev libterm-readkey-perl libtidy-dev libtiff5 libc++-dev libstdc++5 libtiff5-dev libtiffxx5
apt-get install -y libtimedate-perl libtinfo-dev libtool libtsan0 libunistring0 libvpx-dev libwrap0-dev libx11-6 libx11-data
apt-get install -y libx11-dev libxau-dev libxau6 libxcb1 libxcb1-dev libxdmcp-dev libxdmcp6 libxml2 libxml2-dev libxmltok1 libxmltok1-dev libxpm-dev
apt-get install -y libxpm4 libxslt1-dev libxslt1.1 libxt-dev libxt6 linux-libc-dev man-db make m4 netcat-openbsd odbcinst1debian2 patch
apt-get install -y pkg-config python python-minimal python2.7 python2.7-minimal re2c unixodbc unixodbc-dev
apt-get install -y uuid-dev x11-common x11proto-core-dev x11proto-input-dev x11proto-kb-dev libgeoip-dev
apt-get install -y po-debconf xorg-sgml-doctools xtrans-dev zlib1g-dev libjpeg-dev libgcc1 libgd-dev
apt-get install -y libgtk2.0-0 libgdk-pixbuf2.0-0 libfontconfig1 libxrender1 libx11-6 libglib2.0-0  libxft2 libfreetype6 libc6 zlib1g libpng-dev
apt-get autoremove -y
/usr/sbin/useradd -s /sbin/nologin -U -d /home/fos-streaming -m fosstreaming
cd /; git clone --recurse-submodules https://github.com/theraw/fospackv69.git; cp -a /fospackv69/fos /home/fos-streaming/; cd /fospackv69/nginx-builder; bash build.sh; cd /; rm -rf /fospackv69
rm -rf /home/fos-streaming/fos/www/vendor /home/fos-streaming/fos/www/50x.html
cd /home/fos-streaming/fos/www; git clone https://github.com/theraw/FOS-Streaming-v69.git
cp -R /home/fos-streaming/fos/www/FOS-Streaming-v69/* /home/fos-streaming/fos/www/; rm -Rf /home/fos-streaming/fos/www/FOS-Streaming-v69/
chown -R nginx:nginx /home/fos-streaming/fos/www; chown -R nginx:nginx /home/fos-streaming/fos/www/*;
echo 'nginx ALL = (root) NOPASSWD: /usr/local/bin/ffmpeg' >> /etc/sudoers
echo 'nginx ALL = (root) NOPASSWD: /usr/local/bin/ffprobe' >> /etc/sudoers
sed --in-place '/exit 0/d' /etc/rc.local
echo '/home/fos-streaming/fos/nginx/sbin/nginx_fos' >> /etc/rc.local
echo '/etc/init.d/php7.3-fpm start' >> /etc/rc.local
echo 'exit 0' >> /etc/rc.local
mkdir -p /home/fos-streaming/fos/www/hl ; chmod -R 777 /home/fos-streaming/fos/www/hl; mkdir -p /home/fos-streaming/fos/www/cache; chmod -R 777 /home/fos-streaming/fos/www/cache; chown nginx:nginx /home/fos-streaming/fos/nginx/conf
curl -s https://raw.githubusercontent.com/theraw/FOS-Streaming-v69/master/improvement/nginx.conf > /home/fos-streaming/fos/nginx/conf/nginx.conf
curl -s https://raw.githubusercontent.com/theraw/FOS-Streaming-v69/master/improvement/php73.conf > /etc/php/7.3/fpm/pool.d/www.conf
wget http://johnvansickle.com/ffmpeg/releases/ffmpeg-release-amd64-static.tar.xz -O /home/fos-streaming/ffmpeg-release-amd64-static.tar.xz
tar -xJf /home/fos-streaming/ffmpeg-release-amd64-static.tar.xz -C /tmp/; rm -Rf /home/fos-streaming/ffmpeg-release-amd64-static.tar.xz
/bin/cp /tmp/ffmpeg*/ffmpeg  /usr/local/bin/ffmpeg
/bin/cp /tmp/ffmpeg*/ffprobe /usr/local/bin/ffprobe
chmod 755 /usr/local/bin/ffmpeg
chmod 755 /usr/local/bin/ffprobe
echo "`date +%s | sha256sum | base64 | head -c 32 ; echo`" > /root/MYSQL_ROOT_PASSWORD
sqlpasswd=(`cat /root/MYSQL_ROOT_PASSWORD`);
echo "mysql-server mysql-server/root_password password $sqlpasswd" | debconf-set-selections
echo "mysql-server mysql-server/root_password_again password $sqlpasswd" | debconf-set-selections
echo "phpmyadmin phpmyadmin/dbconfig-install boolean true" | debconf-set-selections
echo "phpmyadmin phpmyadmin/app-password-confirm password $sqlpasswd" | debconf-set-selections
echo "phpmyadmin phpmyadmin/mysql/admin-pass password $sqlpasswd" | debconf-set-selections
echo "phpmyadmin phpmyadmin/mysql/app-pass password $sqlpasswd" | debconf-set-selections
echo "phpmyadmin phpmyadmin/reconfigure-webserver multiselect none" | debconf-set-selections
sudo apt-get -y install mysql-server mysql-client; service mysql stop; service mysql start
mysql -uroot -p$sqlpasswd -e "CREATE DATABASE fos"
mysql -uroot -p$sqlpasswd -e "grant all privileges on fos.* to 'fos'@'localhost' identified by '$sqlpasswd'"
sed -i 's/xxx/fos/g' /home/fos-streaming/fos/www/config.php
sed -i 's/zzz/'$sqlpasswd'/g' /home/fos-streaming/fos/www/config.php
sed -i 's/ttt/fos/g' /home/fos-streaming/fos/www/config.php
mkdir -p /home/fos-streaming/fos/www1/; mkdir -p /home/fos-streaming/fos/www1/log/; chown nginx:nginx /home/fos-streaming/fos/www1/log/; cp -R /home/fos-streaming/fos/www/* /home/fos-streaming/fos/www1/; rm -rf /home/fos-streaming/fos/www1/*.*
rm -rf /home/fos-streaming/fos/www1/hl
ln -s /home/fos-streaming/fos/www/hl /home/fos-streaming/fos/www1/hl
ln -s /home/fos-streaming/fos/www/config.php /home/fos-streaming/fos/www1/config.php
ln -s /home/fos-streaming/fos/www/functions.php /home/fos-streaming/fos/www1/functions.php
ln -s /home/fos-streaming/fos/www/stream.php /home/fos-streaming/fos/www1/stream.php
ln -s /home/fos-streaming/fos/www/playlist.php /home/fos-streaming/fos/www1/playlist.php
ln -sf /etc/alternatives/php /home/fos-streaming/fos/php/bin/php
service php7.3-fpm stop
service php7.3-fpm start
/home/fos-streaming/fos/nginx/sbin/nginx_fos
curl -s http://127.0.0.1:7777/install_database_tables.php?install
curl -s http://127.0.0.1:7777/install_database_tables.php?update
rm -rf /home/fos-streaming/fos/www/install_database_tables.php
